{% set name = "acctaudem" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RyanMcCarthy-NOAA/accTauDEM/archive/{{ version }}.tar.gz
  sha256: b35bac0ea056991aefe93a4330a8574e171f7d562c7e6e909f95335b01758e6b

build:
  number: 4
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make  # [linux]
    - cmake  # [linux]
  host:
    - libgdal
    - mpich  # [linux]
    - msmpi  # [win]
  run:
    - libgdal
    - mpich  # [linux]
    - msmpi  # [win]

test:
  commands:
    - test -f $PREFIX/bin/accd8flowdir
    - if not exist %LIBRARY_BIN%\\accD8FlowDir.exe exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\accD8FlowDir.lib exit 1  # [win]

about:
  home: http://hydrology.usu.edu/taudem
  license: GPL-3.0-only
  license_file: license.txt
  summary: Accelerated Terrain Analysis Using Digital Elevation Models (TauDEM)
  description: TauDEM is a suite of Digital Elevation Model (DEM) tools for the extraction and analysis of hydrologic information from topography as represented by a DEM.
  doc_url: https://hydrology.usu.edu/taudem/taudem5/documentation.html
  dev_url: https://github.com/cybergis/cybergis-toolkit

extra:
  recipe-maintainers:
    - RyanMcCarthy-NOAA
